### ISSUE TITLE
Refresh data during the day

### ISSUE THREAD

**Issue by messageexplorer** [tsdaemon/ha-lviv-poweroff#3]
I have next issue, if LOE changes schedule during day, integration pick up these changes only after integration reload. Can be it fixed somehow?

**Comment by gresuk** [comment]
теж замітив що не працює, тільки вчора поставив інтеграцію)))

**Comment by DarkFeniXZp** [comment]
Щось не працює у періодичному оновленні данних з сайту. Хоча, як я зрозумів, оновлення повинно бути кожні 600 с. Як вже писали раніше - тільки перезавантаження інтеграції надає нові данні. Без цього або взагалі немає данних, або вони переносяться на наступний день.

**Comment by DarkFeniXZp** [comment]
> > Щось не працює у періодичному оновленні данних з сайту. Хоча, як я зрозумів, оновлення повинно бути кожні 600 с. Як вже писали раніше - тільки перезавантаження інтеграції надає нові данні. Без цього або взагалі немає данних, або вони переносяться на наступний день.
> 
> Так, є теж така проблема тому я це вирішив "колхозно", зробив автоматизацію яка перевантажує інтеграцію кожні пів години.
> 
> `alias: Перезавантаження Інтеграції description: "" triggers:
> 
> * at:
>   
>   * "00:00:00"
>   * "00:30:00"
>   * "01:00:00"
>   * "01:30:00"
>   * "02:00:00"
>   * "02:30:00"
>   * "03:00:00"
>   * "03:30:00"
>   * "04:00:00"
>   * "04:30:00"
>   * "05:00:00"
>   * "05:30:00"
>   * "06:00:00"
>   * "06:30:00"
>   * "07:00:00"
>   * "07:30:00"
>   * "08:00:00"
>   * "08:30:00"
>   * "09:00:00"
>   * "09:30:00"
>   * "10:00:00"
>   * "10:30:00"
>   * "11:00:00"
>   * "11:30:00"
>   * "12:00:00"
>   * "12:30:00"
>   * "13:00:00"
>   * "13:30:00"
>   * "14:00:00"
>   * "14:30:00"
>   * "15:00:00"
>   * "15:30:00"
>   * "16:00:00"
>   * "16:30:00"
>   * "17:00:00"
>   * "17:30:00"
>   * "18:00:00"
>   * "18:30:00"
>   * "19:00:00"
>   * "19:30:00"
>   * "20:00:00"
>   * "20:30:00"
>   * "21:00:00"
>   * "21:30:00"
>   * "22:00:00"
>   * "22:30:00"
>   * "23:00:00"
>   * "23:30:00"
>     trigger: time
>     alias: Оновлення графіків Відключеннь Електроенергії
>     id: LOE
>     conditions: []
>     actions:
> * alias: LOE
>   if:
>   
>   * condition: trigger
>     id:
>     
>     * LOE
>       then:
>   * action: homeassistant.reload_config_entry
>     data: {}
>     target:
>     entity_id:
>     - sensor.power_state
>     mode: single
>     `

Дякую за код перезавантаження інтеграції, чогось не знайшов потрібної служби, мовляв, немає штатної, треба ледь не через curl запити. Спробую.
P.S. А чого тригер не зробити:
trigger: time_pattern
minutes: "30"

**Comment by gresuk** [comment]
Дуже вам дякую. це працює...

alias: Перезавантаження Інтеграції Lviv Power Offline
description: Перезавантажує інтеграцію кожні 30 хвилин
triggers:
  - minutes: /30
    trigger: time_pattern
conditions: []
actions:
  - target:
      entity_id: sensor.power_state
    action: homeassistant.reload_config_entry
    data: {}
mode: single

**Comment by dabakovich** [comment]
Всім привіт!

Виглядає так, що ~я~ AI agent пофіксив цю проблему з автооновленням. В оригінальній лібі закладено інтервал оновлення 600 секунд (10 хвилин), але цей функціонал був зломаний, та не працював.

Можете тестувати при бажанні: https://github.com/dabakovich/ha-lviv-poweroff

Крім того, там додані відсутні групи, а також дані скрапаються напряму з Львівобленерго (тепер додає хвилини в графік, якщо початок кінець відключення припадає на половину години).

Фікси додав тільки вчора, тому щось не працюватиме, то створюйте PR.

#11
